### ISSUE TITLE
TextSerializationWriter results in System.Net.Http.HttpRequestException

### ISSUE THREAD

**Issue by jasonjoh** [microsoft/kiota-serialization-text-dotnet#82]
```
An exception of type 'System.Net.Http.HttpRequestException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Error while copying content to a stream.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.ObjectDisposedException : Cannot access a closed Stream.
   at System.ThrowHelper.ThrowObjectDisposedException_StreamClosed(String objectName)
   at System.IO.MemoryStream.CopyToAsync(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.StreamToStreamCopy.CopyAsync(Stream source, Stream destination, Int32 bufferSize, Boolean disposeSource, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at System.Net.Http.HttpContent.<<CopyToAsync>g__WaitAsync|56_0>d.MoveNext()
```

Cause:
https://github.com/microsoft/kiota-serialization-text-dotnet/blob/e37cdf88af1f9e6e836c44a52faa1e5c02c91684/src/TextSerializationWriter.cs#L33-L38

- `_stream?.Dispose()` closes the stream.
- `writer?.Dispose()` also closes the stream (so just removing the `_stream?.Dispose()` call won't suffice)

Fix:

- Remove `_stream?.Dispose()` line.
- In `TextSerializationWriter` constructor, pass `leaveOpen: true` to the constructor of the `StreamWriter`.:

    ```csharp
    writer = new(_stream, leaveOpen: true);
    ```

**Comment by jasonjoh** [comment]
Ah should also add that the stream position needs to be reset as well. So the `GetSerializedContent` method should be:


```csharp
public Stream GetSerializedContent()
{
    writer.Flush();
    _stream.Position = 0;
    return _stream;
}
```
